# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'weather.ui'
#
# Created by: PyQt5 UI code generator 5.10.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_weatherDlg(object):
    def setupUi(self, weatherDlg):
        weatherDlg.setObjectName("weatherDlg")
        weatherDlg.setEnabled(True)
        weatherDlg.resize(706, 557)
        weatherDlg.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.verticalLayout = QtWidgets.QVBoxLayout(weatherDlg)
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label = QtWidgets.QLabel(weatherDlg)
        font = QtGui.QFont()
        font.setFamily("Arial Black")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.horizontalLayout.addWidget(self.label)
        self.provinceComboBox = QtWidgets.QComboBox(weatherDlg)
        self.provinceComboBox.setObjectName("provinceComboBox")
        self.horizontalLayout.addWidget(self.provinceComboBox)
        self.label_2 = QtWidgets.QLabel(weatherDlg)
        font = QtGui.QFont()
        font.setFamily("Arial Black")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        font.setKerning(True)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.horizontalLayout.addWidget(self.label_2)
        self.cityComboBox = QtWidgets.QComboBox(weatherDlg)
        self.cityComboBox.setObjectName("cityComboBox")
        self.horizontalLayout.addWidget(self.cityComboBox)
        self.horizontalLayout_3.addLayout(self.horizontalLayout)
        self.iplabel = QtWidgets.QLabel(weatherDlg)
        font = QtGui.QFont()
        font.setFamily("Arial Black")
        font.setPointSize(12)
        font.setBold(True)
        font.setItalic(False)
        font.setUnderline(False)
        font.setWeight(75)
        font.setStrikeOut(False)
        font.setKerning(False)
        self.iplabel.setFont(font)
        self.iplabel.setTabletTracking(False)
        self.iplabel.setText("")
        self.iplabel.setTextFormat(QtCore.Qt.AutoText)
        self.iplabel.setObjectName("iplabel")
        self.horizontalLayout_3.addWidget(self.iplabel)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem)
        self.curentCityButton = QtWidgets.QToolButton(weatherDlg)
        self.curentCityButton.setText("")
        self.curentCityButton.setIconSize(QtCore.QSize(32, 32))
        self.curentCityButton.setAutoRaise(True)
        self.curentCityButton.setObjectName("curentCityButton")
        self.horizontalLayout_3.addWidget(self.curentCityButton)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.queryButton = QtWidgets.QToolButton(weatherDlg)
        self.queryButton.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("C:/Users/HY-PC/.designer/backup/pic/query.jpg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.queryButton.setIcon(icon)
        self.queryButton.setIconSize(QtCore.QSize(32, 32))
        self.queryButton.setAutoRaise(True)
        self.queryButton.setObjectName("queryButton")
        self.horizontalLayout_2.addWidget(self.queryButton)
        self.horizontalLayout_3.addLayout(self.horizontalLayout_2)
        self.verticalLayout.addLayout(self.horizontalLayout_3)
        self.textBrowser = QtWidgets.QTextBrowser(weatherDlg)
        self.textBrowser.setContextMenuPolicy(QtCore.Qt.NoContextMenu)
        self.textBrowser.setObjectName("textBrowser")
        self.verticalLayout.addWidget(self.textBrowser)

        self.retranslateUi(weatherDlg)
        QtCore.QMetaObject.connectSlotsByName(weatherDlg)

    def retranslateUi(self, weatherDlg):
        _translate = QtCore.QCoreApplication.translate
        weatherDlg.setWindowTitle(_translate("weatherDlg", "Dialog"))
        self.label.setText(_translate("weatherDlg", "省份:"))
        self.label_2.setText(_translate("weatherDlg", "城市:"))
        self.curentCityButton.setToolTip(_translate("weatherDlg", "<html><head/><body><p><span style=\" font-size:12pt; color:#00aaff;\">当前城市</span></p></body></html>"))
        self.curentCityButton.setWhatsThis(_translate("weatherDlg", "<html><head/><body><p><span style=\" font-size:12pt; color:#00aaff;\">当前城市</span></p></body></html>"))
        self.queryButton.setToolTip(_translate("weatherDlg", "<html><head/><body><p><span style=\" font-size:12pt; font-weight:600; color:#00aaff;\">查询</span></p></body></html>"))

