# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'friendList.ui'
#
# Created by: PyQt5 UI code generator 5.10.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_friendListDlg(object):
    def setupUi(self, friendListDlg):
        friendListDlg.setObjectName("friendListDlg")
        friendListDlg.resize(250, 677)
        friendListDlg.setMinimumSize(QtCore.QSize(250, 650))
        friendListDlg.setMaximumSize(QtCore.QSize(450, 1000))
        font = QtGui.QFont()
        font.setStyleStrategy(QtGui.QFont.PreferDefault)
        friendListDlg.setFont(font)
        friendListDlg.setMouseTracking(False)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("C:/Users/HY-PC/.designer/pic/logo.jpg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        friendListDlg.setWindowIcon(icon)
        friendListDlg.setAutoFillBackground(True)
        self.gridLayout = QtWidgets.QGridLayout(friendListDlg)
        self.gridLayout.setObjectName("gridLayout")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.findlabel = QtWidgets.QLabel(friendListDlg)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(13)
        font.setBold(True)
        font.setWeight(75)
        self.findlabel.setFont(font)
        self.findlabel.setTextFormat(QtCore.Qt.PlainText)
        self.findlabel.setObjectName("findlabel")
        self.horizontalLayout.addWidget(self.findlabel)
        self.findlineEdit = QtWidgets.QLineEdit(friendListDlg)
        self.findlineEdit.setEnabled(True)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.findlineEdit.setFont(font)
        self.findlineEdit.setEchoMode(QtWidgets.QLineEdit.Normal)
        self.findlineEdit.setObjectName("findlineEdit")
        self.horizontalLayout.addWidget(self.findlineEdit)
        self.AddUserButton = QtWidgets.QToolButton(friendListDlg)
        self.AddUserButton.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.AddUserButton.setText("")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap("C:/Users/HY-PC/.designer/backup/pic/adduser.ico"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.AddUserButton.setIcon(icon1)
        self.AddUserButton.setIconSize(QtCore.QSize(24, 24))
        self.AddUserButton.setAutoRaise(True)
        self.AddUserButton.setObjectName("AddUserButton")
        self.horizontalLayout.addWidget(self.AddUserButton)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.friendTreeWidget = QtWidgets.QTreeWidget(friendListDlg)
        self.friendTreeWidget.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.friendTreeWidget.setFrameShadow(QtWidgets.QFrame.Raised)
        self.friendTreeWidget.setLineWidth(0)
        self.friendTreeWidget.setTextElideMode(QtCore.Qt.ElideNone)
        self.friendTreeWidget.setVerticalScrollMode(QtWidgets.QAbstractItemView.ScrollPerItem)
        self.friendTreeWidget.setObjectName("friendTreeWidget")
        self.friendTreeWidget.headerItem().setText(0, "好友列表")
        self.verticalLayout.addWidget(self.friendTreeWidget)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.weatherButton = QtWidgets.QToolButton(friendListDlg)
        font = QtGui.QFont()
        font.setBold(False)
        font.setItalic(False)
        font.setUnderline(False)
        font.setWeight(50)
        font.setStrikeOut(False)
        self.weatherButton.setFont(font)
        self.weatherButton.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.weatherButton.setMouseTracking(False)
        self.weatherButton.setToolTip("<html><head/><body><p><span style=\" font-size:12pt; color:#00aaff;\">天气</span></p></body></html>")
        self.weatherButton.setToolTipDuration(-1)
        self.weatherButton.setStatusTip("")
        self.weatherButton.setWhatsThis("")
        self.weatherButton.setAccessibleName("")
        self.weatherButton.setAccessibleDescription("")
        self.weatherButton.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.weatherButton.setAutoFillBackground(False)
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap("C:/Users/HY-PC/.designer/backup/pic/weather.ico"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.weatherButton.setIcon(icon2)
        self.weatherButton.setIconSize(QtCore.QSize(32, 32))
        self.weatherButton.setToolButtonStyle(QtCore.Qt.ToolButtonIconOnly)
        self.weatherButton.setAutoRaise(True)
        self.weatherButton.setObjectName("weatherButton")
        self.horizontalLayout_2.addWidget(self.weatherButton)
        self.calendarButton = QtWidgets.QToolButton(friendListDlg)
        self.calendarButton.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.calendarButton.setText("")
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap("C:/Users/HY-PC/.designer/backup/pic/calendar.ico"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.calendarButton.setIcon(icon3)
        self.calendarButton.setIconSize(QtCore.QSize(32, 32))
        self.calendarButton.setAutoRaise(True)
        self.calendarButton.setObjectName("calendarButton")
        self.horizontalLayout_2.addWidget(self.calendarButton)
        self.snackButton = QtWidgets.QToolButton(friendListDlg)
        self.snackButton.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.snackButton.setText("")
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap("C:/Users/HY-PC/.designer/backup/pic/snack.ico"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.snackButton.setIcon(icon4)
        self.snackButton.setIconSize(QtCore.QSize(32, 32))
        self.snackButton.setAutoRaise(True)
        self.snackButton.setObjectName("snackButton")
        self.horizontalLayout_2.addWidget(self.snackButton)
        self.TetrisButton = QtWidgets.QToolButton(friendListDlg)
        self.TetrisButton.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.TetrisButton.setText("")
        icon5 = QtGui.QIcon()
        icon5.addPixmap(QtGui.QPixmap("C:/Users/HY-PC/.designer/backup/pic/Tetris.ico"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.TetrisButton.setIcon(icon5)
        self.TetrisButton.setIconSize(QtCore.QSize(32, 32))
        self.TetrisButton.setAutoRaise(True)
        self.TetrisButton.setObjectName("TetrisButton")
        self.horizontalLayout_2.addWidget(self.TetrisButton)
        self.gobangButton = QtWidgets.QToolButton(friendListDlg)
        self.gobangButton.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.gobangButton.setText("")
        icon6 = QtGui.QIcon()
        icon6.addPixmap(QtGui.QPixmap("C:/Users/HY-PC/.designer/backup/pic/gobang.ico"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.gobangButton.setIcon(icon6)
        self.gobangButton.setIconSize(QtCore.QSize(32, 32))
        self.gobangButton.setAutoRaise(True)
        self.gobangButton.setObjectName("gobangButton")
        self.horizontalLayout_2.addWidget(self.gobangButton)
        self.fileButton = QtWidgets.QToolButton(friendListDlg)
        self.fileButton.setText("")
        icon7 = QtGui.QIcon()
        icon7.addPixmap(QtGui.QPixmap("C:/Users/HY-PC/.designer/backup/pic/file.ico"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.fileButton.setIcon(icon7)
        self.fileButton.setIconSize(QtCore.QSize(32, 32))
        self.fileButton.setAutoRaise(True)
        self.fileButton.setObjectName("fileButton")
        self.horizontalLayout_2.addWidget(self.fileButton)
        self.setingButton = QtWidgets.QToolButton(friendListDlg)
        self.setingButton.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.setingButton.setText("")
        icon8 = QtGui.QIcon()
        icon8.addPixmap(QtGui.QPixmap("C:/Users/HY-PC/.designer/backup/pic/seting.ico"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.setingButton.setIcon(icon8)
        self.setingButton.setIconSize(QtCore.QSize(32, 32))
        self.setingButton.setAutoRaise(True)
        self.setingButton.setObjectName("setingButton")
        self.horizontalLayout_2.addWidget(self.setingButton)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.verticalLayout.addLayout(self.verticalLayout_2)
        self.gridLayout.addLayout(self.verticalLayout, 0, 0, 1, 1)

        self.retranslateUi(friendListDlg)
        QtCore.QMetaObject.connectSlotsByName(friendListDlg)

    def retranslateUi(self, friendListDlg):
        _translate = QtCore.QCoreApplication.translate
        friendListDlg.setWindowTitle(_translate("friendListDlg", "微聊"))
        self.findlabel.setText(_translate("friendListDlg", "查找"))
        self.findlineEdit.setToolTip(_translate("friendListDlg", "<html><head/><body><p><span style=\" font-size:12pt; color:#00aaff;\">查找好友</span></p></body></html>"))
        self.AddUserButton.setToolTip(_translate("friendListDlg", "<html><head/><body><p><span style=\" font-size:12pt; color:#00aaff;\">添加好友</span></p></body></html>"))
        self.weatherButton.setText(_translate("friendListDlg", "..."))
        self.calendarButton.setToolTip(_translate("friendListDlg", "<html><head/><body><p><span style=\" font-size:12pt; color:#00aaff;\">日历</span></p></body></html>"))
        self.snackButton.setToolTip(_translate("friendListDlg", "<html><head/><body><p><span style=\" font-size:12pt; color:#00aaff;\">贪吃蛇</span></p></body></html>"))
        self.TetrisButton.setToolTip(_translate("friendListDlg", "<html><head/><body><p><span style=\" font-size:12pt; color:#00aaff;\">俄罗斯方块</span></p></body></html>"))
        self.gobangButton.setToolTip(_translate("friendListDlg", "<html><head/><body><p><span style=\" font-size:12pt; color:#00aaff;\">五子棋</span></p></body></html>"))
        self.fileButton.setToolTip(_translate("friendListDlg", "<html><head/><body><p><span style=\" font-size:12pt; color:#00aaff;\">文件传输</span></p></body></html>"))
        self.setingButton.setToolTip(_translate("friendListDlg", "<html><head/><body><p><span style=\" font-size:12pt; color:#00aaff;\">设置</span></p></body></html>"))

